name: Build Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Publish Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          # GITHUB_ENV file is sourced by subsequent steps
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          # ENV is 'beta' if it's a pre-release or contains 'beta' in name
          if [[ "${{ github.event.release.prerelease }}" == "true" || "${{ github.event.release.tag_name }}" =~ .*beta.* ]]
          then
            echo "ENV=beta" >> $GITHUB_ENV
          else
            echo "ENV=prod" >> $GITHUB_ENV
          fi
      - name: Install JDK
        run: apt update && apt install -y openjdk-17-jdk
      - name: Build Image
        run: |
          ./gradlew buildBootImage -Pversion=$VERSION
      - name: Tag Image
        run: |
          docker tag simple-web-app:$VERSION ghcr.io/vmware-tanzu-learning/simple-web-app:$VERSION
      - name: Prune dangling images
        run: docker image prune -f
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish version to GitHub Package Registry
        run: |
          docker push ghcr.io/vmware-tanzu-learning/simple-web-app:$VERSION
